services:
  - type: web
    name: Web
    env: docker
    healthCheckPath: /api/auth
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: Database
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: REDIS_URL
        fromService:
          type: redis
          name: Redis
          property: connectionString
      - fromGroup: TryOnify
  - type: worker
    name: Sidekiq
    env: docker
    dockerfilePath: ./sidekiq/Dockerfile
    scaling:
      minInstances: 1
      maxInstances: 2
      targetMemoryPercent: 60
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: Database
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: REDIS_URL
        fromService:
          type: redis
          name: Redis
          property: connectionString
      - fromGroup: TryOnify
  - type: cron
    name: FetchOrders
    env: docker
    schedule: 0 */12 * * *
    dockerCommand: rake fetch_orders
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: Database
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: REDIS_URL
        fromService:
          type: redis
          name: Redis
          property: connectionString
      - fromGroup: TryOnify
  - type: cron
    name: CreatePayments
    env: docker
    schedule: 30 */6 * * *
    dockerCommand: rake create_payments
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: Database
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: REDIS_URL
        fromService:
          type: redis
          name: Redis
          property: connectionString
      - fromGroup: TryOnify
  - type: cron
    name: UpdateOrders
    env: docker
    schedule: 0 * * * *
    dockerCommand: rake update_orders
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: Database
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: REDIS_URL
        fromService:
          type: redis
          name: Redis
          property: connectionString
      - fromGroup: TryOnify
  - type: redis
    name: Redis
    ipAllowList:
      - source: 0.0.0.0
        description: everywhere
    maxmemoryPolicy: noeviction

  # Staging
  - type: web
    name: web-staging
    env: docker
    healthCheckPath: /api/auth
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: database-staging
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: REDIS_URL
        fromService:
          type: redis
          name: redis-staging
          property: connectionString
      - fromGroup: tryonify-staging
  - type: worker
    name: sidekiq-staging
    env: docker
    dockerfilePath: ./sidekiq/Dockerfile
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: database-staging
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: REDIS_URL
        fromService:
          type: redis
          name: redis-staging
          property: connectionString
      - fromGroup: tryonify-staging
  - type: cron
    name: fetch-orders-staging
    env: docker
    schedule: 0 */12 * * *
    dockerCommand: rake fetch_orders
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: database-staging
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: REDIS_URL
        fromService:
          type: redis
          name: redis-staging
          property: connectionString
      - fromGroup: tryonify-staging
  - type: cron
    name: create-payments-staging
    env: docker
    schedule: 30 */6 * * *
    dockerCommand: rake create_payments
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: database-staging
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: REDIS_URL
        fromService:
          type: redis
          name: redis-staging
          property: connectionString
      - fromGroup: tryonify-staging
  - type: cron
    name: update-orders-staging
    env: docker
    schedule: 0 * * * *
    dockerCommand: rake update_orders
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: database-staging
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: REDIS_URL
        fromService:
          type: redis
          name: redis-staging
          property: connectionString
      - fromGroup: TryOnify
  - type: redis
    name: redis-staging
    ipAllowList:
      - source: 0.0.0.0
        description: everywhere
    maxmemoryPolicy: noeviction

databases:
  - name: Database
    databaseName: tryonify_production
  - name: database-staging
    databaseName: tryonify_staging