# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "eaf955909864a101d588b085c0893d75"
name = "TryOnify"
application_url = "https://web-qla9.onrender.com/"
embedded = true
handle = "tryonify"

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  uri = "https://hkdk.events/g1x7mimhhn4tyh"
  topics = [
    "app/uninstalled",
    "bulk_operations/finish",
    "orders/create",
    "orders/updated",
    "orders/edited",
    "payment_terms/update",
    "returns/request",
    "returns/approve",
    "returns/reopen",
    "returns/decline",
    "returns/close",
    "returns/cancel",
    "shop/update"
  ]

  [[webhooks.subscriptions]]
  uri = "/api/webhooks/customers_data_request"
  compliance_topics = [ "customers/data_request" ]

  [[webhooks.subscriptions]]
  uri = "/api/webhooks/customers_redact"
  compliance_topics = [ "customers/redact" ]

  [[webhooks.subscriptions]]
  uri = "/api/webhooks/shop_redact"
  compliance_topics = [ "shop/redact" ]

[auth]
redirect_urls = [ "https://web-qla9.onrender.com/api/auth/callback" ]

[access_scopes]
scopes = "read_all_orders,read_customers,read_draft_orders,read_orders,read_payment_mandate,read_payment_terms,read_products,read_purchase_options,read_validations,read_returns,write_orders,write_payment_terms,write_payment_mandate,write_products,write_purchase_options,write_returns,write_pixels"

[app_proxy]
url = "https://web-qla9.onrender.com/app_proxy"
subpath = "trial"
prefix = "a"

[pos]
embedded = false
