# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "aceba7032efaaa5d1d69673e7c22e1de"
name = "TryOnify (Development)"
handle = "tryonify-dev"
application_url = "https://tryonify.ngrok.io/"
embedded = true

[build]
automatically_update_urls_on_dev = false
dev_store_url = "tryonify-dev.myshopify.com"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_all_orders,read_customers,read_draft_orders,read_orders,read_payment_mandate,read_payment_terms,read_products,read_purchase_options,read_validations,write_orders,write_payment_mandate,write_products,write_purchase_options"

[auth]
redirect_urls = [
  "https://tryonify.ngrok.io/auth/callback",
  "https://tryonify.ngrok.io/auth/shopify/callback",
  "https://tryonify.ngrok.io/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

  [webhooks.privacy_compliance]
  customer_deletion_url = "https://tryonify.ngrok.io/api/webhooks/customers_redact"
  customer_data_request_url = "https://tryonify.ngrok.io/api/webhooks/customers_data_request"
  shop_deletion_url = "https://tryonify.ngrok.io/api/webhooks/shop_redact"

[app_proxy]
url = "https://tryonify.ngrok.io/app_proxy"
subpath = "trial"
prefix = "a"

[pos]
embedded = false
