# This file stores configurations for your Shopify app.

scopes = "read_products, write_products, read_orders, write_orders, read_purchase_options, write_purchase_options, read_all_orders, read_payment_terms, read_customers"
