inherit_gem:
  rubocop-shopify: rubocop.yml

AllCops:
  TargetRubyVersion: 3.1
  Exclude:
    - "db/**/*"
    - "bin/**/*"
    - "test/tmp/**/*"
    - "vendor/bundle/**/*"
    - "spec/**/stubs.rb"

Style/MethodCallWithArgsParentheses:
  Exclude:
    - "**/Gemfile"
    - "test/**/*"

Style/ClassAndModuleChildren:
  Exclude:
    - "test/**/*"
