# frozen_string_literal: true

source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby "3.1.2"

gem 'dotenv-rails', '~> 2.7', '>= 2.7.6', groups: [:development, :test]

# Bundle edge Rails instead: gem "rails", github: "rails/rails", branch: "main"
gem "rails", "~> 7.0.3"

# The original asset pipeline for Rails [https://github.com/rails/sprockets-rails]
gem "sprockets-rails"

# Use Postgres as the database for Active Record
gem "pg", "~> 1.4", ">= 1.4.3"

# Use the Puma web server [https://github.com/puma/puma]
gem "puma", "~> 5.0"

# Use JavaScript with ESM import maps [https://github.com/rails/importmap-rails]
gem "importmap-rails"

# Hotwire's SPA-like page accelerator [https://turbo.hotwired.dev]
gem "turbo-rails"

# Hotwire's modest JavaScript framework [https://stimulus.hotwired.dev]
gem "stimulus-rails"

# Build JSON APIs with ease [https://github.com/rails/jbuilder]
gem "jbuilder"

# Use Redis adapter to run Action Cable in production
gem "redis", "~> 4.0"

# Use Kredis to get higher-level data types in Redis [https://github.com/rails/kredis]
# gem "kredis"

# Use Active Model has_secure_password [https://guides.rubyonrails.org/active_model_basics.html#securepassword]
# gem "bcrypt", "~> 3.1.7"

gem "tzinfo-data"

# Reduces boot times through caching; required in config/boot.rb
gem "bootsnap", require: false

# Use Sass to process CSS
# gem "sassc-rails"

# Use Active Storage variants [https://guides.rubyonrails.org/active_storage_overview.html#transforming-images]
# gem "image_processing", "~> 1.2"

group :development, :test do
  # See https://guides.rubyonrails.org/debugging_rails_applications.html#debugging-with-the-debug-gem
  gem "debug", platforms: [:mri, :mingw, :x64_mingw]
  gem 'rspec-rails', '~> 6.0', '>= 6.0.1'
  gem 'webmock', '~> 3.18', '>= 3.18.1'
  gem 'rubocop-rails', '~> 2.15', '>= 2.15.1', require: false
  gem 'rubocop-rspec', '~> 2.11', '>= 2.11.1'
  gem 'vcr', '~> 6.1'
  gem 'factory_bot_rails', '~> 6.2'
  gem 'faker', '~> 3.0'
end

group :development do
  # Use console on exceptions pages [https://github.com/rails/web-console]
  gem "web-console"

  # Add speed badges [https://github.com/MiniProfiler/rack-mini-profiler]
  # gem "rack-mini-profiler"

  # Speed up commands on slow machines / big apps [https://github.com/rails/spring]
  # gem "spring"

  gem "rubocop"
  gem "rubocop-shopify"
  gem "bullet"
end

group :test do
  # Use system testing [https://guides.rubyonrails.org/testing.html#system-testing]
  gem "capybara"
  gem "selenium-webdriver"
  gem "webdrivers"
end

gem "shopify_app", "~> 21.6"
gem 'sidekiq', '~> 6.5', '>= 6.5.1'

# Klaviyo integration
gem 'klaviyo', '~> 2.4'

# Slack Integration
gem 'slack-ruby-client', '~> 2.0'

# ActiveRecord Pagination
gem 'kaminari', '~> 1.2', '>= 1.2.2'

# Automatically convert snakecase to camelcase
gem 'olive_branch', '~> 4.0', '>= 4.0.1'

# CORS
gem 'rack-cors', '~> 1.1', '>= 1.1.1'

# Email
gem 'postmark-rails', '~> 0.22.1'

# Performance Monitoring
gem "sentry-ruby"
gem "sentry-rails"
gem 'rest-client', '~> 2.1'

# DB Search
gem 'pg_search', '~> 2.3', '>= 2.3.6'